#!/usr/bin/env node
/**
 * Render a parsed paper into a browsable HTML page.
 *
 *   npm run preview -- "Physics MJ25 21"
 *   npm run preview -- --all
 *
 * The generated page loads the REAL js/render/*.js and css/style.css by
 * relative path, so what you see is what the app will draw — not a
 * facsimile. Open the file directly; no server needed.
 *
 * This is a stopgap for having no database yet: the same renderer will be
 * fed from Supabase once the schema migration lands, and this harness can
 * go away then.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mergePaper, parseAnswerPaper, parseQuestionPaper } from '../src/latex/index.js';
import type { ParsedPaper } from '../src/latex/types.js';

const here = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(here, '..', '..');
const PAPERS_DIR = join(REPO, 'Updated Latex FIles For Web');
const OUT_DIR = join(REPO, 'backend', 'reports', 'preview');

// Order matters: escape defines the helpers the rest use, and the facade
// composes the four renderers, so it loads last.
const RENDER_SCRIPTS = [
  'escape.js',
  'block-renderer.js',
  'part-renderer.js',
  'options-renderer.js',
  'mark-scheme-renderer.js',
  'solution-renderer.js',
  'question-renderer.js',
];

function findPair(dir: string): { qp: string; qa: string | null } | null {
  const tex = readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.tex'));
  const qp = tex.find((f) => /qp/i.test(f));
  const qa = tex.find((f) => /qa/i.test(f));
  if (!qp) return null;
  return { qp: join(dir, qp), qa: qa ? join(dir, qa) : null };
}

function parseFolder(dir: string): ParsedPaper {
  const pair = findPair(dir);
  if (!pair) throw new Error(`No QP .tex found in ${dir}`);
  const qp = parseQuestionPaper(readFileSync(pair.qp, 'utf8'));
  return pair.qa ? mergePaper(qp, parseAnswerPaper(readFileSync(pair.qa, 'utf8'))) : qp;
}

function buildPage(paper: ParsedPaper, title: string): string {
  // The renderer sources and stylesheet are INLINED rather than linked.
  // Relative paths out of this folder only resolve under file://; the
  // moment the preview is served by a static server rooted anywhere but
  // the repo root, they 404 and the page renders blank. Inlining makes the
  // file work when opened directly, served from any root, or emailed to
  // someone. It is regenerated by `npm run preview`, so it never goes
  // stale against js/render/.
  const scripts = RENDER_SCRIPTS.map((f) => {
    const source = readFileSync(join(REPO, 'js', 'render', f), 'utf8');
    return `<script>\n/* ---- js/render/${f} ---- */\n${source}\n</script>`;
  }).join('\n');

  const css = readFileSync(join(REPO, 'css', 'style.css'), 'utf8');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview — ${title}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<style>
/* ---- css/style.css (inlined verbatim) ---- */
${css}
</style>
<style>
  /* Preview chrome only — not part of the app's stylesheet. */
  body { margin: 0; padding: 24px; }
  .pv-head { margin-bottom: 20px; padding-bottom: 12px; border-bottom: 2px solid #ddd; }
  .pv-warn { background: #fff4e5; border-left: 4px solid #e69500; padding: 10px 14px; margin: 8px 0; }
  .pv-q { border: 1px solid #e2e2e2; border-radius: 10px; padding: 18px; margin-bottom: 26px; }
  .pv-qhead { display: flex; gap: 14px; align-items: baseline; flex-wrap: wrap; margin-bottom: 12px; }
  .pv-qnum { font-weight: 700; font-size: 1.05rem; }
  .pv-topic { color: #666; font-style: italic; }
  .pv-marks { margin-left: auto; font-variant-numeric: tabular-nums; }
  .pv-tabs { display: flex; gap: 8px; margin: 14px 0 10px; }
  .pv-tab { padding: 5px 12px; border: 1px solid #ccc; border-radius: 999px; cursor: pointer; font-size: .85rem; background: #fafafa; }
  .pv-tab[aria-selected="true"] { background: #222; color: #fff; border-color: #222; }
  .pv-panel[hidden] { display: none; }
</style>
</head>
<body>
<div class="pv-head">
  <h1>${title}</h1>
  <div id="pvMeta"></div>
  <div id="pvWarnings"></div>
</div>
<div id="pvBody"></div>

<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
${scripts}
<script id="paperData" type="application/json">${JSON.stringify(paper).replace(/</g, '\\u003c')}</script>
<script>
(function () {
  // Fail loudly instead of rendering a blank page: if the renderer did not
  // load, say so on screen rather than only in the console.
  if (typeof SWRender === 'undefined' || !SWRender.QuestionRenderer) {
    document.getElementById('pvBody').innerHTML =
      '<div class="pv-warn"><strong>Renderer failed to load.</strong> ' +
      'Regenerate this file with <code>npm run preview</code>.</div>';
    return;
  }
  var paper = JSON.parse(document.getElementById('paperData').textContent);
  // Guidance is a 4-column-paper extra; the preview shows it because the
  // point here is to inspect everything the parser produced.
  var renderer = new SWRender.QuestionRenderer({ showGuidance: true });

  var p = paper.paper;
  document.getElementById('pvMeta').innerHTML = p
    ? '<code>' + p.paperId + '</code> — subject ' + p.subjectCode + ' · paper ' + p.paper +
      ' · variant ' + p.variant + ' · ' + p.session + ' ' + p.year +
      ' — ' + paper.questions.length + ' questions'
    : '<i>paper id could not be read</i>';

  document.getElementById('pvWarnings').innerHTML = paper.warnings.map(function (w) {
    return '<div class="pv-warn"><strong>' + w.code + '</strong> — ' + w.message + '</div>';
  }).join('');

  document.getElementById('pvBody').innerHTML = paper.questions.map(function (q, i) {
    var card = renderer.toCard(q);
    var msRows = card.markSchemeRows.map(function (row) {
      return row.isBanner
        ? '<tr class="ms-banner-row"><td colspan="3">' + row.answer + '</td></tr>'
        : '<tr><td>' + row.part + '</td><td>' + row.answer + '</td><td>' + row.marks + '</td></tr>';
    }).join('');

    return '<article class="pv-q">' +
      '<div class="pv-qhead">' +
        '<span class="pv-qnum">Question ' + card.number + '</span>' +
        '<span class="pv-topic">' + (card.topic || '') + '</span>' +
        '<span class="pv-marks">' + card.marks + ' marks · ' + card.kind + '</span>' +
      '</div>' +
      '<div class="pv-tabs" data-q="' + i + '">' +
        '<span class="pv-tab" aria-selected="true" data-panel="q">Question</span>' +
        '<span class="pv-tab" aria-selected="false" data-panel="ms">Mark scheme</span>' +
        '<span class="pv-tab" aria-selected="false" data-panel="ex">Exemplar</span>' +
      '</div>' +
      '<div class="pv-panel" data-q="' + i + '" data-panel="q">' +
        '<div class="question-shell">' + card.questionHtml + '</div></div>' +
      '<div class="pv-panel" data-q="' + i + '" data-panel="ms" hidden>' +
        '<table class="mstable"><thead><tr><th>Part</th><th>Expected answer</th><th>Marks</th></tr></thead>' +
        '<tbody>' + (msRows || '<tr><td colspan="3"><i>No mark scheme.</i></td></tr>') + '</tbody></table></div>' +
      '<div class="pv-panel" data-q="' + i + '" data-panel="ex" hidden>' +
        '<div class="exemplar-box">' + card.exemplarHtml + '</div></div>' +
    '</article>';
  }).join('');

  document.addEventListener('click', function (e) {
    var tab = e.target.closest ? e.target.closest('.pv-tab') : null;
    if (!tab) return;
    var group = tab.parentNode.getAttribute('data-q');
    var want = tab.getAttribute('data-panel');
    Array.prototype.forEach.call(tab.parentNode.children, function (t) {
      t.setAttribute('aria-selected', String(t === tab));
    });
    Array.prototype.forEach.call(
      document.querySelectorAll('.pv-panel[data-q="' + group + '"]'),
      function (panel) { panel.hidden = panel.getAttribute('data-panel') !== want; }
    );
  });

  // Same delimiters the app uses, so math behaves identically here.
  renderMathInElement(document.body, {
    delimiters: [
      { left: '$$', right: '$$', display: true },
      { left: '\\\\[', right: '\\\\]', display: true },
      { left: '$', right: '$', display: false },
      { left: '\\\\(', right: '\\\\)', display: false }
    ],
    throwOnError: false
  });
})();
</script>
</body>
</html>
`;
}

const argv = process.argv.slice(2);
const all = argv.includes('--all');
const target = argv.filter((a) => !a.startsWith('--')).join(' ');

const folders = existsSync(PAPERS_DIR)
  ? readdirSync(PAPERS_DIR).filter((d) => statSync(join(PAPERS_DIR, d)).isDirectory()).sort()
  : [];

let chosen: string[];
if (all) {
  chosen = folders.map((f) => join(PAPERS_DIR, f));
} else if (target) {
  const words = target.toLowerCase().split(/\s+/).filter(Boolean);
  const hits = folders.filter((f) => words.every((w) => f.toLowerCase().includes(w)));
  if (hits.length !== 1) {
    console.error(
      hits.length === 0
        ? `No paper matching "${target}".`
        : `"${target}" matches ${hits.length}: ${hits.join(', ')}`,
    );
    console.error(`\nAvailable:\n  ${folders.join('\n  ')}`);
    process.exit(1);
  }
  chosen = [join(PAPERS_DIR, hits[0])];
} else {
  console.log(`Usage: npm run preview -- "Physics MJ25 21"   (or --all)\n`);
  console.log(`Papers:\n  ${folders.join('\n  ')}`);
  process.exit(0);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const dir of chosen) {
  const name = basename(dir);
  const paper = parseFolder(dir);
  const out = join(OUT_DIR, `${name}.html`);
  writeFileSync(out, buildPage(paper, name), 'utf8');
  console.log(`${name.padEnd(22)} -> ${out}`);
}
console.log(`\nOpen one in a browser (no server needed).`);
